name: Glibc
on:
  push:
    paths:
      - '.github/workflows/glibc.yml'
      - 'src/**'
      - 'config.mak.def'
      - 'Makefile'
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Ubuntu Glibc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Env Version
        run: |
          gcc --version
          ld --version
          ldd --version
      - name: Run Test
        run: make -j`nproc`
      - name: Show Test Result
        run: cat src/REPORT
